#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname $0)"

name=uptimerobot
curl --config ../.curlrc https://uptimerobot.com/inc/files/ips/IPv4andIPv6.txt -o $TEMPFILE

grepip $TEMPFILE | iprange >| $name.ipv4
grepip6 $TEMPFILE | cidr-merger  >| $name.ipv6
