#!/usr/bin/env bash
#set -eo pipefail

cd "$(dirname $0)"
TEMPFILE=$(mktemp)

name=bingbot
curl --config ../.curlrc https://www.bing.com/toolbox/bingbot.json -o $TEMPFILE

jq -r .prefixes[].ipv4Prefix $TEMPFILE | grepip | iprange >| $name.ipv4
