#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname $0)"
TEMPFILE=$(mktemp)

name=binaryedge
curl --config ../.curlrc https://api.binaryedge.io/v1/minions -o $TEMPFILE

jq .scanners $TEMPFILE | grepip | iprange -1 >| $name.ipv4
