#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname $0)"
TEMPFILE=$(mktemp)

name=bitbucket
curl --config ../.curlrc https://ip-ranges.atlassian.com -o $TEMPFILE

jq .items $TEMPFILE | gron | grep cidr | sponge $TEMPFILE

grepip $TEMPFILE | iprange >| $name.ipv4
grepip6 $TEMPFILE | cidr-merger >| $name.ipv6
