#!/usr/bin/env bash

cd "$(dirname $0)"

ASNS=(
  32934
  54115
  63293
  #149642
)

name=facebook

for asn in "${ASNS[@]}"
do
  echo "ASN: $asn"
  curl -sL --fail https://raw.githubusercontent.com/ipverse/asn-ip/master/as/$asn/ipv4-aggregated.txt -o $name-$asn.ipv4.tmp || exit 0
  curl -sL --fail https://raw.githubusercontent.com/ipverse/asn-ip/master/as/$asn/ipv6-aggregated.txt -o $name-$asn.ipv6.tmp || exit 0
done

cat *.ipv4.tmp | grepip | iprange >| $name.ipv4
cat *.ipv6.tmp | grepip6 | cidr-merger  >| $name.ipv6

