#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname $0)"

name=doh
curl --config ../.curlrc -o $name.ipv4 https://raw.githubusercontent.com/dibdot/DoH-IP-blocklists/master/doh-ipv4.txt
curl --config ../.curlrc -o $name.ipv6 https://raw.githubusercontent.com/dibdot/DoH-IP-blocklists/master/doh-ipv6.txt

