#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname $0)"
TEMPFILE=$(mktemp)

# run
name=duckduckgobot
curl --config ../.curlrc https://raw.githubusercontent.com/duckduckgo/duckduckgo-help-pages/master/_docs/results/duckduckbot.md -o $TEMPFILE
grepip $TEMPFILE | iprange -1 | sponge $name.ipv4
