#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname $0)"
TEMPFILE=$(mktemp)

name=tailscale-derp
curl --config ../.curlrc https://login.tailscale.com/derpmap/default -o $TEMPFILE

jq -r '.Regions[].Nodes[].IPv4' $TEMPFILE | iprange >| $name.ipv4
jq -r '.Regions[].Nodes[].IPv6' $TEMPFILE | cidr-merger >| $name.ipv6

dig +short @1.1.1.1 login.tailscale.com >| tailscale-coordination.ipv4
dig +short @1.1.1.1 controlplane.tailscale.com >> tailscale-coordination.ipv4
dig +short @1.1.1.1 log.tailscale.com >> tailscale-coordination.ipv4
dig +short @1.1.1.1 log.tailscale.io >> tailscale-coordination.ipv4

iprange tailscale-coordination.ipv4 | sponge tailscale-coordination.ipv4


