#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname $0)"
TEMPFILE=$(mktemp)

name=cloudflare
curl --config ../.curlrc https://www.cloudflare.com/ips-v4 -o $TEMPFILE.4
curl --config ../.curlrc https://www.cloudflare.com/ips-v6 -o $TEMPFILE.6

grepip $TEMPFILE.4 | iprange >| $name.ipv4
grepip6 $TEMPFILE.6 | cidr-merger >| $name.ipv6
