#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname $0)"
TEMPFILE=$(mktemp)

name=github
curl --config ../.curlrc https://api.github.com/meta -o $TEMPFILE

jq . $TEMPFILE | sponge $TEMPFILE
grepip $TEMPFILE | iprange >| $name.ipv4
grepip6 $TEMPFILE | cidr-merger >| $name.ipv6
