#!/usr/bin/env bash

cd "$(dirname $0)"

name=github
curl -sL --fail https://api.github.com/meta -o $name.json.tmp

if [ ! $? -eq 0 ]; then
    exit 0
fi

# Nice & tidy
jq . $name.json.tmp | sponge $name.json.tmp

grepip < $name.json.tmp | iprange > $name.ipv4
grepip6 < $name.json.tmp | cidr-merger > $name.ipv6
