#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname $0)"
TEMPFILE=$(mktemp)

# All google ips
name=google
curl --config ../.curlrc https://raw.githubusercontent.com/lord-alfred/ipranges/main/google/ipv4.txt -o $TEMPFILE
iprange $TEMPFILE >| $name.ipv4

curl --config ../.curlrc https://raw.githubusercontent.com/lord-alfred/ipranges/main/google/ipv6.txt -o $TEMPFILE
cidr-merger $TEMPFILE >| $name.ipv6

# Google bots
name=googlebot
curl --config ../.curlrc https://developers.google.com/search/apis/ipranges/googlebot.json -o $TEMPFILE

# Nice & tidy
jq .prefixes $TEMPFILE | sponge $TEMPFILE

grepip $TEMPFILE | iprange >| $name.ipv4
grepip6 $TEMPFILE | cidr-merger >| $name.ipv6
