#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname $0)"
TEMPFILE=$(mktemp)

# All google ips
name=google
curl --config ../.curlrc https://raw.githubusercontent.com/lord-alfred/ipranges/main/google/ipv4.txt -o $TEMPFILE
iprange $TEMPFILE >| $name.ipv4

curl --config ../.curlrc https://raw.githubusercontent.com/lord-alfred/ipranges/main/google/ipv6.txt -o $TEMPFILE
cidr-merger $TEMPFILE >| $name.ipv6

# Google bots
name=googlebot
curl --config ../.curlrc https://developers.google.com/search/apis/ipranges/googlebot.json -o $TEMPFILE

# Nice & tidy
jq .prefixes $TEMPFILE | sponge $TEMPFILE

grepip $TEMPFILE | iprange >| $name.ipv4
grepip6 $TEMPFILE | cidr-merger >| $name.ipv6

# Google cloud
https://www.gstatic.com/ipranges/cloud.json
curl --config ../.curlrc https://developers.google.com/search/apis/ipranges/googlebot.json -o $TEMPFILE

cat $TEMPFILE | jq '.prefixes[] | select( .scope | contains("us-") )' | jq .ipv4Prefix | grepip | sponge googlecloud-usa.ipv4
cat $TEMPFILE | jq '.prefixes[] | select( .scope | contains("africa-") )' | jq .ipv4Prefix | grepip | sponge googlecloud-africa.ipv4
cat $TEMPFILE | jq '.prefixes[] | select( .scope | contains("asia-") )' | jq .ipv4Prefix | grepip | sponge googlecloud-asia.ipv4
cat $TEMPFILE | jq '.prefixes[] | select( .scope | contains("australia-") )' | jq .ipv4Prefix | grepip | sponge googlecloud-australia.ipv4
cat $TEMPFILE | jq '.prefixes[] | select( .scope | contains("europe-west") )' | jq .ipv4Prefix | grepip | sponge googlecloud-europe-west.ipv4
cat $TEMPFILE | jq '.prefixes[] | select( .scope | contains("europe-north") )' | jq .ipv4Prefix | grepip | sponge googlecloud-europe-north.ipv4
cat $TEMPFILE | jq '.prefixes[] | select( .scope | contains("global") )' | jq .ipv4Prefix | grepip | sponge googlecloud-global.ipv4
cat $TEMPFILE | jq '.prefixes[] | select( .scope | contains("me-") )' | jq .ipv4Prefix | grepip | sponge googlecloud-middleeast.ipv4
cat $TEMPFILE | jq '.prefixes[] | select( .scope | contains("northamerica-") )' | jq .ipv4Prefix | grepip | sponge googlecloud-northamerica.ipv4
cat $TEMPFILE | jq '.prefixes[] | select( .scope | contains("southamerica-") )' | jq .ipv4Prefix | grepip | sponge googlecloud-southamerica.ipv4

fd 'googlecloud-.*ipv4' -x bash -c 'echo {.}; grepip {} | iprange | sponge {.}.ipv4'
