#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname $0)"
TEMPFILE=$(mktemp)

name=paloaltonetworks

# as/54538/ipv4-aggregated.txt:   # PALO ALTO NETWORKS
# as/64280/ipv4-aggregated.txt:   # Palo Alto Networks, Inc
# as/396421/ipv4-aggregated.txt:  # PALO ALTO NETWORKS
# https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA14u000000wleTCAQ&lang=en_US%E2%80%A9

# Ipranges
cat << EOF > $TEMPFILE
# Global:
https://www.abuseipdb.com/check-block/205.210.31.0/24
https://www.abuseipdb.com/check-block/198.235.24.0/24

# Global Research:
https://www.abuseipdb.com/check-block/35.203.210.0/24
https://www.abuseipdb.com/check-block/35.203.211.0/24
https://www.abuseipdb.com/check-block/162.216.149.0/24
https://www.abuseipdb.com/check-block/162.216.150.0/24

# Known Assets Monitoring (KAM):
https://www.abuseipdb.com/check-block/172.105.147.0/24
https://www.abuseipdb.com/check-block/144.86.173.0/24
https://www.abuseipdb.com/check-block/65.154.226.0/24
EOF


grepip $TEMPFILE | iprange --min-prefix 24 >| $name.ipv4
