#!/usr/bin/env bash
#set -eo pipefail

cd "$(dirname $0)"
TEMPFILE=$(mktemp)

name=openai-searchbot
curl --config ../.curlrc https://openai.com/searchbot.json -o $TEMPFILE
jq -r .prefixes[].ipv4Prefix $TEMPFILE | grepip | iprange >| $name.ipv4

name=openai-gptbot
curl --config ../.curlrc https://openai.com/gptbot.json -o $TEMPFILE
jq -r .prefixes[].ipv4Prefix $TEMPFILE | grepip | iprange >| $name.ipv4

name=openai-chatgpt-user
curl --config ../.curlrc https://openai.com/chatgpt-user.json -o $TEMPFILE
jq -r .prefixes[].ipv4Prefix $TEMPFILE | grepip | iprange >| $name.ipv4
